### ISSUE TITLE
[1.25.0] OSS backend fails to build on FreeBSD

### ISSUE THREAD

**Issue by BSDKaffee** [kcat/openal-soft#1215]
OS: FreeBSD 14.3 amd64
Compiler: Clang 19.1.7

```[ 63% 90/109] /usr/local/libexec/ccache/c++ -DALC_API="__attribute__((visibility(\"protected\")))" -DAL_ALEXT_PROTOTYPES -DAL_API="__attribute__((visibility(\"protected\")))" -DAL_BUILD_LIBRARY -DOpenAL_EXPORTS -D_LIBCPP_HARDENING_MODE=_LIBCPP_HARDENING_MODE_FAST -I/wrkdirs/usr/ports/audio/openal-soft/work/openal-soft-1.25.0/include -I/wrkdirs/usr/ports/audio/openal-soft/work/.build -I/wrkdirs/usr/ports/audio/openal-soft/work/openal-soft-1.25.0 -I/wrkdirs/usr/ports/audio/openal-soft/work/openal-soft-1.25.0/common -I/wrkdirs/usr/ports/audio/openal-soft/work/openal-soft-1.25.0/gsl/include -I/wrkdirs/usr/ports/audio/openal-soft/work/openal-soft-1.25.0/fmt-11.2.0/include -isystem /usr/local/include/dbus-1.0 -isystem /usr/local/lib/dbus-1.0/include -O2 -pipe -D__STDC_NO_THREADS__ -fstack-protector-strong -fno-strict-aliasing -O2 -pipe -D__STDC_NO_THREADS__ -fstack-protector-strong -fno-strict-aliasing   -DNDEBUG -std=gnu++20 -fPIC -fvisibility=hidden -Wunused -Wall -Wextra -Wshadow -Wconversion -Wcast-align -Wpedantic -Wformat -Wformat=2 -Wold-style-cast -Wnon-virtual-dtor -Woverloaded-virtual -Werror=undef -Werror=format-security -ftrivial-auto-var-init=pattern -fno-math-errno -pthread -MD -MT CMakeFiles/OpenAL.dir/alc/backends/oss.cpp.o -MF CMakeFiles/OpenAL.dir/alc/backends/oss.cpp.o.d -o CMakeFiles/OpenAL.dir/alc/backends/oss.cpp.o -c /wrkdirs/usr/ports/audio/openal-soft/work/openal-soft-1.25.0/alc/backends/oss.cpp
FAILED: [code=1] CMakeFiles/OpenAL.dir/alc/backends/oss.cpp.o 
/usr/local/libexec/ccache/c++ -DALC_API="__attribute__((visibility(\"protected\")))" -DAL_ALEXT_PROTOTYPES -DAL_API="__attribute__((visibility(\"protected\")))" -DAL_BUILD_LIBRARY -DOpenAL_EXPORTS -D_LIBCPP_HARDENING_MODE=_LIBCPP_HARDENING_MODE_FAST -I/wrkdirs/usr/ports/audio/openal-soft/work/openal-soft-1.25.0/include -I/wrkdirs/usr/ports/audio/openal-soft/work/.build -I/wrkdirs/usr/ports/audio/openal-soft/work/openal-soft-1.25.0 -I/wrkdirs/usr/ports/audio/openal-soft/work/openal-soft-1.25.0/common -I/wrkdirs/usr/ports/audio/openal-soft/work/openal-soft-1.25.0/gsl/include -I/wrkdirs/usr/ports/audio/openal-soft/work/openal-soft-1.25.0/fmt-11.2.0/include -isystem /usr/local/include/dbus-1.0 -isystem /usr/local/lib/dbus-1.0/include -O2 -pipe -D__STDC_NO_THREADS__ -fstack-protector-strong -fno-strict-aliasing -O2 -pipe -D__STDC_NO_THREADS__ -fstack-protector-strong -fno-strict-aliasing   -DNDEBUG -std=gnu++20 -fPIC -fvisibility=hidden -Wunused -Wall -Wextra -Wshadow -Wconversion -Wcast-align -Wpedantic -Wformat -Wformat=2 -Wold-style-cast -Wnon-virtual-dtor -Woverloaded-virtual -Werror=undef -Werror=format-security -ftrivial-auto-var-init=pattern -fno-math-errno -pthread -MD -MT CMakeFiles/OpenAL.dir/alc/backends/oss.cpp.o -MF CMakeFiles/OpenAL.dir/alc/backends/oss.cpp.o.d -o CMakeFiles/OpenAL.dir/alc/backends/oss.cpp.o -c /wrkdirs/usr/ports/audio/openal-soft/work/openal-soft-1.25.0/alc/backends/oss.cpp
In file included from /wrkdirs/usr/ports/audio/openal-soft/work/openal-soft-1.25.0/alc/backends/oss.cpp:23:
In file included from /wrkdirs/usr/ports/audio/openal-soft/work/openal-soft-1.25.0/alc/backends/oss.h:4:
In file included from /wrkdirs/usr/ports/audio/openal-soft/work/openal-soft-1.25.0/alc/backends/base.h:4:
In file included from /usr/include/c++/v1/chrono:969:
In file included from /usr/include/c++/v1/__chrono/formatter.h:16:
In file included from /usr/include/c++/v1/__chrono/convert_to_tm.h:23:
In file included from /usr/include/c++/v1/__chrono/statically_widen.h:17:
In file included from /usr/include/c++/v1/__format/concepts.h:16:
In file included from /usr/include/c++/v1/__format/format_parse_context.h:16:
In file included from /usr/include/c++/v1/string_view:941:
In file included from /usr/include/c++/v1/algorithm:1842:
In file included from /usr/include/c++/v1/__algorithm/for_each.h:16:
In file included from /usr/include/c++/v1/__ranges/movable_box.h:21:
In file included from /usr/include/c++/v1/optional:1294:
In file included from /usr/include/c++/v1/memory:940:
In file included from /usr/include/c++/v1/__memory/allocator.h:15:
In file included from /usr/include/c++/v1/__memory/allocate_at_least.h:13:
/usr/include/c++/v1/__memory/allocator_traits.h:328:5: error: no matching function for call to '__construct_at'
  328 |     std::__construct_at(__p, std::forward<_Args>(__args)...);
      |     ^~~~~~~~~~~~~~~~~~~
/usr/include/c++/v1/vector:961:21: note: in instantiation of function template specialization 'std::allocator_traits<std::allocator<(anonymous namespace)::DevMap>>::construct<(anonymous namespace)::DevMap, std::string, std::string_view &, void, 0>' requested here
  961 |     __alloc_traits::construct(this->__alloc(), std::__to_address(__tx.__pos_), std::forward<_Args>(__args)...);
      |                     ^
/usr/include/c++/v1/vector:1555:5: note: in instantiation of function template specialization 'std::vector<(anonymous namespace)::DevMap>::__construct_one_at_end<std::string, std::string_view &>' requested here
 1555 |     __construct_one_at_end(std::forward<_Args>(__args)...);
      |     ^
/wrkdirs/usr/ports/audio/openal-soft/work/openal-soft-1.25.0/alc/backends/oss.cpp:166:30: note: in instantiation of function template specialization 'std::vector<(anonymous namespace)::DevMap>::emplace_back<std::string, std::string_view &>' requested here
  166 |     const auto &entry = list.emplace_back(std::move(newname), path);
      |                              ^
/usr/include/c++/v1/__memory/construct_at.h:47:58: note: candidate template ignored: substitution failure [with _Tp = (anonymous namespace)::DevMap, _Args = <std::string, std::string_view &>]: no viable conversion from 'std::string_view' to 'std::string' (aka 'basic_string<char>')
   46 | template <class _Tp, class... _Args, class = decltype(::new(std::declval<void*>()) _Tp(std::declval<_Args>()...))>
      |                                                                                        ~~~
   47 | _LIBCPP_HIDE_FROM_ABI _LIBCPP_CONSTEXPR_SINCE_CXX20 _Tp* __construct_at(_Tp* __location, _Args&&... __args) {
      |                                                          ^
/wrkdirs/usr/ports/audio/openal-soft/work/openal-soft-1.25.0/alc/backends/oss.cpp:214:48: error: no viable conversion from 'basic_string_view<char>' to 'std::string' (aka 'basic_string<char>')
  214 |         devlist.insert(devlist.begin(), DevMap{GetDefaultName(), defdev});
      |                                                ^~~~~~~~~~~~~~~~
/usr/include/c++/v1/string:999:71: note: candidate constructor not viable: no known conversion from 'basic_string_view<char>' to 'const string &' for 1st argument
  999 |   _LIBCPP_CONSTEXPR_SINCE_CXX20 _LIBCPP_STRING_INTERNAL_MEMORY_ACCESS basic_string(const basic_string& __str)
      |                                                                       ^            ~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/include/c++/v1/string:1019:55: note: candidate constructor not viable: no known conversion from 'basic_string_view<char>' to 'string &&' for 1st argument
 1019 |   _LIBCPP_HIDE_FROM_ABI _LIBCPP_CONSTEXPR_SINCE_CXX20 basic_string(basic_string&& __str)
      |                                                       ^            ~~~~~~~~~~~~~~~~~~~~
/usr/include/c++/v1/string:1058:55: note: candidate constructor template not viable: no known conversion from 'basic_string_view<char>' to 'const char *' for 1st argument
 1058 |   _LIBCPP_HIDE_FROM_ABI _LIBCPP_CONSTEXPR_SINCE_CXX20 basic_string(const _CharT* __s)
      |                                                       ^            ~~~~~~~~~~~~~~~~~
/usr/include/c++/v1/string:1198:55: note: candidate constructor not viable: no known conversion from 'basic_string_view<char>' to 'initializer_list<char>' for 1st argument
 1198 |   _LIBCPP_HIDE_FROM_ABI _LIBCPP_CONSTEXPR_SINCE_CXX20 basic_string(initializer_list<_CharT> __il)
      |                                                       ^            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/include/c++/v1/string:989:64: note: explicit constructor is not a candidate
  989 |   _LIBCPP_HIDE_FROM_ABI _LIBCPP_CONSTEXPR_SINCE_CXX20 explicit basic_string(const allocator_type& __a)
      |                                                                ^
/usr/include/c++/v1/string:1154:93: note: explicit constructor is not a candidate
 1154 |   _LIBCPP_METHOD_TEMPLATE_IMPLICIT_INSTANTIATION_VIS _LIBCPP_CONSTEXPR_SINCE_CXX20 explicit basic_string(const _Tp& __t)
      |                                                                                             ^
2 errors generated.```

**Comment by kcat** [comment]
Should be fixed with commit 278d1dc4d607b84e4e7b2d93af094d7932588962. Can you double-check?

**Comment by BSDKaffee** [comment]
That partially fixed it, but another error popped up:
```
FAILED: [code=1] CMakeFiles/OpenAL.dir/alc/backends/oss.cpp.o 
/usr/local/libexec/ccache/c++ -DALC_API="__attribute__((visibility(\"protected\")))" -DAL_ALEXT_PROTOTYPES -DAL_API="__attribute__((visibility(\"protected\")))" -DAL_BUILD_LIBRARY -DOpenAL_EXPORTS -D_LIBCPP_HARDENING_MODE=_LIBCPP_HARDENING_MODE_FAST -I/wrkdirs/usr/ports/audio/openal-soft/work/openal-soft-1.25.0/include -I/wrkdirs/usr/ports/audio/openal-soft/work/.build -I/wrkdirs/usr/ports/audio/openal-soft/work/openal-soft-1.25.0 -I/wrkdirs/usr/ports/audio/openal-soft/work/openal-soft-1.25.0/common -I/wrkdirs/usr/ports/audio/openal-soft/work/openal-soft-1.25.0/gsl/include -I/wrkdirs/usr/ports/audio/openal-soft/work/openal-soft-1.25.0/fmt-11.2.0/include -isystem /usr/local/include/dbus-1.0 -isystem /usr/local/lib/dbus-1.0/include -O2 -pipe -D__STDC_NO_THREADS__ -fstack-protector-strong -fno-strict-aliasing -O2 -pipe -D__STDC_NO_THREADS__ -fstack-protector-strong -fno-strict-aliasing   -DNDEBUG -std=gnu++20 -fPIC -fvisibility=hidden -Wunused -Wall -Wextra -Wshadow -Wconversion -Wcast-align -Wpedantic -Wformat -Wformat=2 -Wold-style-cast -Wnon-virtual-dtor -Woverloaded-virtual -Werror=undef -Werror=format-security -ftrivial-auto-var-init=pattern -fno-math-errno -pthread -MD -MT CMakeFiles/OpenAL.dir/alc/backends/oss.cpp.o -MF CMakeFiles/OpenAL.dir/alc/backends/oss.cpp.o.d -o CMakeFiles/OpenAL.dir/alc/backends/oss.cpp.o -c /wrkdirs/usr/ports/audio/openal-soft/work/openal-soft-1.25.0/alc/backends/oss.cpp
/wrkdirs/usr/ports/audio/openal-soft/work/openal-soft-1.25.0/alc/backends/oss.cpp:218:48: error: no viable conversion from 'basic_string_view<char>' to 'std::string' (aka 'basic_string<char>')
  218 |         devlist.insert(devlist.begin(), DevMap{GetDefaultName(), defdev});
      |                                                ^~~~~~~~~~~~~~~~
/usr/include/c++/v1/string:999:71: note: candidate constructor not viable: no known conversion from 'basic_string_view<char>' to 'const string &' for 1st argument
  999 |   _LIBCPP_CONSTEXPR_SINCE_CXX20 _LIBCPP_STRING_INTERNAL_MEMORY_ACCESS basic_string(const basic_string& __str)
      |                                                                       ^            ~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/include/c++/v1/string:1019:55: note: candidate constructor not viable: no known conversion from 'basic_string_view<char>' to 'string &&' for 1st argument
 1019 |   _LIBCPP_HIDE_FROM_ABI _LIBCPP_CONSTEXPR_SINCE_CXX20 basic_string(basic_string&& __str)
      |                                                       ^            ~~~~~~~~~~~~~~~~~~~~
/usr/include/c++/v1/string:1058:55: note: candidate constructor template not viable: no known conversion from 'basic_string_view<char>' to 'const char *' for 1st argument
 1058 |   _LIBCPP_HIDE_FROM_ABI _LIBCPP_CONSTEXPR_SINCE_CXX20 basic_string(const _CharT* __s)
      |                                                       ^            ~~~~~~~~~~~~~~~~~
/usr/include/c++/v1/string:1198:55: note: candidate constructor not viable: no known conversion from 'basic_string_view<char>' to 'initializer_list<char>' for 1st argument
 1198 |   _LIBCPP_HIDE_FROM_ABI _LIBCPP_CONSTEXPR_SINCE_CXX20 basic_string(initializer_list<_CharT> __il)
      |                                                       ^            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/include/c++/v1/string:989:64: note: explicit constructor is not a candidate
  989 |   _LIBCPP_HIDE_FROM_ABI _LIBCPP_CONSTEXPR_SINCE_CXX20 explicit basic_string(const allocator_type& __a)
      |                                                                ^
/usr/include/c++/v1/string:1154:93: note: explicit constructor is not a candidate
 1154 |   _LIBCPP_METHOD_TEMPLATE_IMPLICIT_INSTANTIATION_VIS _LIBCPP_CONSTEXPR_SINCE_CXX20 explicit basic_string(const _Tp& __t)
      |                                                                                             ^
1 error generated.
```

**Comment by kcat** [comment]
Commit b93a15cc886cda8ce7626e84c637bdaf7c346773 should fix that one now.

**Comment by BSDKaffee** [comment]
After applying both commits there is still an error, unfortunately.
```
FAILED: [code=1] CMakeFiles/OpenAL.dir/alc/backends/oss.cpp.o 
/usr/local/libexec/ccache/c++ -DALC_API="__attribute__((visibility(\"protected\")))" -DAL_ALEXT_PROTOTYPES -DAL_API="__attribute__((visibility(\"protected\")))" -DAL_BUILD_LIBRARY -DOpenAL_EXPORTS -D_LIBCPP_HARDENING_MODE=_LIBCPP_HARDENING_MODE_FAST -I/wrkdirs/usr/ports/audio/openal-soft/work/openal-soft-1.25.0/include -I/wrkdirs/usr/ports/audio/openal-soft/work/.build -I/wrkdirs/usr/ports/audio/openal-soft/work/openal-soft-1.25.0 -I/wrkdirs/usr/ports/audio/openal-soft/work/openal-soft-1.25.0/common -I/wrkdirs/usr/ports/audio/openal-soft/work/openal-soft-1.25.0/gsl/include -I/wrkdirs/usr/ports/audio/openal-soft/work/openal-soft-1.25.0/fmt-11.2.0/include -isystem /usr/local/include/dbus-1.0 -isystem /usr/local/lib/dbus-1.0/include -O2 -pipe -D__STDC_NO_THREADS__ -fstack-protector-strong -fno-strict-aliasing -O2 -pipe -D__STDC_NO_THREADS__ -fstack-protector-strong -fno-strict-aliasing   -DNDEBUG -std=gnu++20 -fPIC -fvisibility=hidden -Wunused -Wall -Wextra -Wshadow -Wconversion -Wcast-align -Wpedantic -Wformat -Wformat=2 -Wold-style-cast -Wnon-virtual-dtor -Woverloaded-virtual -Werror=undef -Werror=format-security -ftrivial-auto-var-init=pattern -fno-math-errno -pthread -MD -MT CMakeFiles/OpenAL.dir/alc/backends/oss.cpp.o -MF CMakeFiles/OpenAL.dir/alc/backends/oss.cpp.o.d -o CMakeFiles/OpenAL.dir/alc/backends/oss.cpp.o -c /wrkdirs/usr/ports/audio/openal-soft/work/openal-soft-1.25.0/alc/backends/oss.cpp
/wrkdirs/usr/ports/audio/openal-soft/work/openal-soft-1.25.0/alc/backends/oss.cpp:218:37: error: reference to non-static member function must be called; did you mean to call it with no arguments?
  218 |         std::ranges::rotate(devlist.begin, iter, iter+1);
      |                             ~~~~~~~~^~~~~
      |                                          ()
/usr/include/c++/v1/vector:1411:26: note: possible target for call
 1411 | vector<_Tp, _Allocator>::begin() _NOEXCEPT {
      |                          ^
/usr/include/c++/v1/vector:610:70: note: possible target for call
  610 |   _LIBCPP_CONSTEXPR_SINCE_CXX20 _LIBCPP_HIDE_FROM_ABI const_iterator begin() const _NOEXCEPT;
      |                                                                      ^
1 error generated.
```

**Comment by BSDKaffee** [comment]
After adding the missing () in https://github.com/kcat/openal-soft/blob/master/alc/backends/oss.cpp#L218, it builds fine.

Thanks for your hard work!

**Comment by kcat** [comment]
Fixed for real with commit 5f0bf631d7d43f568f10065aae561c892c02d43e.
