### ISSUE TITLE
MSVC - ambiguous call to overloaded function

### ISSUE THREAD

**Issue by CaptainHorse** [kcat/openal-soft#376]
Hello again, I've come across some errors during compilation on the latest branch of openal-soft, this doesn't happen in v1.19 branch but I thought I'd report this incase it's important.

OS: Windows 10 1903 64-bit
IDE: Visual Studio Community 2019 Preview (16.5.0 Preview 1.0)
Compiler: MSVC v142
Windows SDK version: 10.0.18362.0

Error:
`openal-soft\common\almalloc.h(269): error C2668: 'al::destroy_n': ambiguous call to overloaded function`

**Comment by kcat** [comment]
Can you post the full error? It should say what's ambiguous about the call. I pushed commit e9ee6dd2396ad48f441878aeeaa4553eed44ce06 which might help, but if not I'll need to see more or all of the compiler's output.

**Comment by CaptainHorse** [comment]
If you mean the note below the error, here it is.
Tried the latest commit, error still present.
```
openal-soft\common\almalloc.h(269): error C2668: 'al::destroy_n': ambiguous call to overloaded function
openal-soft\common\almalloc.h(123): note: could be 'T al::destroy_n<_Ty*,al::FlexArray<HrirArray,16>::index_type,0>(T,N)'
          with
          [
              T=std::array<float2,128> *,
              _Ty=std::array<float2,128>,
              N=al::FlexArray<HrirArray,16>::index_type
          ]
  G:\Microsoft Visual Studio 2019\VC\Tools\MSVC\14.24.28314\include\memory(330): note: or       '_NoThrowFwdIt std::destroy_n<_Ty*,al::FlexArray<HrirArray,16>::index_type>(_NoThrowFwdIt,const _Diff)' [found using argument-dependent lookup]
          with
          [
              _NoThrowFwdIt=std::array<float2,128> *,
              _Ty=std::array<float2,128>,
              _Diff=al::FlexArray<HrirArray,16>::index_type
          ]
  openal-soft\common\almalloc.h(269): note: while trying to match the argument list '(_Ty *, const al::FlexArray<HrirArray,16>::index_type)'
          with
          [
              _Ty=std::array<float2,128>
          ]`
```

**Comment by kcat** [comment]
Should be fixed with commit 819763a6c20cebf8aa7e64421182d3f19269ff13. For some reason, it was considering `std::destroy` as a potential candidate for a `destroy` call in the `al` namespace, even though it shouldn't be callable like that.

**Comment by CaptainHorse** [comment]
Compiles perfectly now. Thank you for such a quick fix! 👏
