### ISSUE TITLE
Battlefield 2 silent crash with 1.21.1 using ambdec and alsoft.ini

### ISSUE THREAD

**Issue by jeremywh7** [kcat/openal-soft#560]
v1.21.0 works fine with the same files, but the game silently crashes for 1.21.1.  The alsoft log ([alsoft-1.21.1 5.1side 24bit44100.txt](https://github.com/kcat/openal-soft/files/6424698/alsoft-1.21.1.5.1side.24bit44100.txt)) seems the same.  Event viewer _Error_ info of the crash:
```
- <System>
  <Provider Name="Application Error" /> 
  <EventID Qualifiers="0">1000</EventID> 
  <Version>0</Version> 
  <Level>2</Level> 
  <Task>100</Task> 
  <Opcode>0</Opcode> 
  <Keywords>0x80000000000000</Keywords> 
  <TimeCreated SystemTime="2021-05-05T00:32:09.5125156Z" /> 
  <EventRecordID>7806</EventRecordID> 
  <Correlation /> 
  <Execution ProcessID="0" ThreadID="0" /> 
  <Channel>Application</Channel> 
  <Computer>ITX</Computer> 
  <Security /> 
  </System>
- <EventData>
  <Data>BF2.exe</Data> 
  <Data>0.0.0.0</Data> 
  <Data>4a8d6629</Data> 
  <Data>soft_oal.dll</Data> 
  <Data>1.21.1.0</Data> 
  <Data>00000000</Data> 
  <Data>c0000005</Data> 
  <Data>00033ca5</Data> 
  <Data>24a8</Data> 
  <Data>01d7414614846145</Data> 
  <Data>C:\Program Files (x86)\EA GAMES\Battlefield 2\BF2.exe</Data> 
  <Data>C:\Program Files (x86)\EA GAMES\Battlefield 2\soft_oal.dll</Data> 
  <Data>a4e288fb-d2cf-44ff-9a8c-271fb290a4d5</Data> 
  <Data /> 
  <Data /> 
  </EventData>
```

**Comment by jeremywh7** [comment]
I should clarify that BF2 loads fine with 1.21.1 if the itu5.1.ambdec file is missing (the log shows it 'failed to load'), but then there is no center channel.  There is one difference around the cpuid detection in the working 1.21.0 versus failing 1.21.1 logs:  [Fwiw, 1.21.0 has extra spaces in the cpu 'Name' field]
```
[ALSOFT] (II) Initializing library v1.21.0-c0cbe602 master
[...]
[ALSOFT] (II) Detected max CPUID function: 0x10 (ext. 0x80000020)
[ALSOFT] (II) Vendor ID: "AuthenticAMD"
[ALSOFT] (II) Name: "AMD Ryzen 7 3700X 8-Core Processor             "
[ALSOFT] (II) Extensions: +SSE +SSE2 +SSE3 +SSE4.1
```
The failing log doesn't have the CPUID part:
```
[ALSOFT] (II) Initializing library v1.21.1-ae4eacf1 master
[...]
[ALSOFT] (II) Vendor ID: "AuthenticAMD"
[ALSOFT] (II) Name: "AMD Ryzen 7 3700X 8-Core Processor"
[ALSOFT] (II) Extensions: +SSE +SSE2 +SSE3 +SSE4.1
```

**Comment by TheMaxus** [comment]
The 1.21.1 also breaks spatial audio in Fallout New Vegas and Fallout 3 and causes frequent crashing.

**Comment by ChthonVII** [comment]
Getting the same thing with Guild Wars 1 via DSOAL. (Hi, again!)
Think I can maybe shed some light: 1.21.1 appears to be happy with an ambdec file if both (a) the distance for all speakers is the same, and (b) the distance value doesn't have too many decimal places. If I violate either of those conditions, I get a hard crash immediately upon launching the program.

**Comment by kcat** [comment]
Yeah, it seems there's a bug in that commit that caused the buffers to not be set and subsequently crash when playback starts. Commit 8d868ff33f1c7ddf4c24e40215731a6d0721d182 should fix that. It won't do anything about the broken spatial audio or frequent crashing in Fallout 3/NV mentioned by @TheMaxus, though.

**Comment by kcat** [comment]
I've set up AppVeyor to produce build artifacts. Every build AppVeyor does will create a zip file containing the OpenAL Soft DLL, the license, and the readme. A given build's artifacts will be removed after 30 days. To get them, go to
https://ci.appveyor.com/project/ChrisRobinson/openal-soft
to see the latest builds, and click on the "job" pertaining to the build you want (`ARCH=Win32, CFG=Release` for the 32-bit Release build, and `ARCH=x64, CFG=Release` for the 64-bit Release build), and from there, click on the `Artifacts` link above the build output.

Standard disclaimers apply, I don't make those and can't test them, so I can't vouch that they actually work as expected. It's mainly there to ensure the code builds, but given that it successfully builds, it should work.

**Comment by ChthonVII** [comment]
Thank you very much for the appveyor link!

Unfortunately, the most recent build is still crashing. We've gone from "Memory at address 00000000 could not be read" to "Memory at address 00000a00 could not be read," so I suspect we're now doing math on a null pointer.

**Comment by kcat** [comment]
That doesn't make much sense for the distance compensation. Does the new DLL work without the ambdec file, or with it having equal distances?

**Comment by ChthonVII** [comment]
Well fudge. I'm getting inconsistent results.

With unequal distances in the ambdec: In 1 of 4 tries, crashed at launch as previously reported. In 3 of 4 tries, got a loud pop when game started, then game worked fine, then game hung and turned to zombie process after normal exit.

With equal distances in ambdec: In 1 of 2 tries, crashed as previously reported. In 1 of 2 tries, loud pop, then worked normally, then zombie process after exit.

With no ambdec at all: In 1 of 1 tries, loud pop, then worked normally, then zombie process after exit.

I'm sorry these results are probably pretty useless for tracking down the bug(s).

**Comment by jeremywh7** [comment]
> Yeah, it seems there's a bug in that commit that caused the buffers to not be set and subsequently crash when playback starts. Commit [8d868ff](https://github.com/kcat/openal-soft/commit/8d868ff33f1c7ddf4c24e40215731a6d0721d182) should fix that.

I just tested the 62e6ce6d73 22may 2021 x86 artifact .dll in BF2 and it is working fine now.  Thanks @kcat!!

> It won't do anything about the broken spatial audio or frequent crashing in Fallout 3/NV 

I guess this needs a separate Issue, or is that not an openal-soft issue?

**Comment by kcat** [comment]
> I guess this needs a separate Issue, or is that not an openal-soft issue?

A separate issue. There's already one for the spatial audio at #561, though I'd need to have more information with the crash for one on that.
