### ISSUE TITLE
Build fails on Fedora (canonical links)

### ISSUE THREAD

**Issue by SirLynix** [kcat/openal-soft#864]
Hi,

First of all, thank you for this amazing library.

I'm updating the openal package on xmake-repo (a package manager for C and C++) and I get a failure on Fedora when testing the package:
```
checkinfo: ...gramdir/core/sandbox/modules/import/core/tool/linker.lua:75: @programdir/core/sandbox/modules/os.lua:273: /usr/bin/ld: /tmp/.xmake0/230622/_062BB6A036A640208D5BC8F5BF9E9520.o: non-canonical reference to canonical protected function `alGetProcAddress' in /github/home/.xmake/packages/o/openal-soft/1.23.1/9ce3a9b6c8dd4564a0392cbb03647f93/lib/libopenal.so
/usr/bin/ld: failed to set dynamic section sizes: bad value
```

The library is compiled using its cmake file and then tested with a simple file using:
```
> /usr/bin/g++ -o /tmp/.xmake0/230622/_062BB6A036A640208D5BC8F5BF9E9520.b /tmp/.xmake0/230622/_062BB6A036A640208D5BC8F5BF9E9520.o -m64 -L/github/home/.xmake/packages/o/openal-soft/1.23.1/9ce3a9b6c8dd4564a0392cbb03647f93/lib -lopenal -ldl -lpthread
```

It's the first time I encounter "canonical reference" issues, do you have maybe an idea where it's coming? Package seemed fine with version 1.22.2

See the CI job here:
https://github.com/xmake-io/xmake-repo/actions/runs/5342427364/jobs/9684239819?pr=2215

Thanks in advance.

**Comment by kcat** [comment]
First I'm hearing about "canonical reference" errors too. From other issues [I've found](https://bugreports.qt.io/browse/QTBUG-103465), it seems to be a binutils bug that was fixed about a year ago for 2.38 and 2.39:

https://sourceware.org/bugzilla/show_bug.cgi?id=29087
https://sourceware.org/bugzilla/show_bug.cgi?id=29377

**Comment by SirLynix** [comment]
The failing CI has binutils 2.39. I tried to run it with last version of Fedora (with binutils 2.40) and it still fails the same unfortunately: <https://github.com/xmake-io/xmake-repo/actions/runs/5345073411/jobs/9690253496>

I have no idea what's going on.

**Comment by SirLynix** [comment]
I fixed it by disabling protected visibility on Fedora (https://github.com/xmake-io/xmake-repo/pull/2215/commits/e1e794a1e06cec961ec1e64ee9932a407694d5cd).

I suppose this bug (as it's probably a bug?) could be detected with a more complex test in the CMakeLists.txt

**Comment by yann-boyer** [comment]
I have the same issue on my openSUSE Tumbleweed dual boot... I hope it'll get fixed.
For now I'll use clang as my toolchain for openal until the issue is resolved.
